### ISSUE TITLE
Unresolved reference: ConnectionInfo

### ISSUE THREAD

**Issue by yueduz** [SlothLabs/kotlin-mail#5]
![2019-04-05 22-43-44 的屏幕截图](https://user-images.githubusercontent.com/1448159/55635890-57e87680-57f4-11e9-8c41-55af990965d0.png)

**Comment by Flaflo** [comment]
The correct class is called "ConnectionInformation"

**Comment by shero1111** [comment]
also doesnt work "ConnectionInformation"

**Comment by Flaflo** [comment]
Worked for me tho

**Comment by tatumalenko** [comment]
It is indeed `ConnectionInformation`, the readme has been corrected accordingly.

**Comment by Flaflo** [comment]
> 
> 
> It is indeed `ConnectionInformation`, the readme has been corrected accordingly.

That means you could close this issue :D
